// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSBm_jojQ3HRt-CI1hFQoyBnZgCuGxv4U',
    appId: '1:1062899694013:web:71a2950cf8ad94d735bad4',
    messagingSenderId: '1062899694013',
    projectId: 'growme-91008',
    authDomain: 'growme-91008.firebaseapp.com',
    storageBucket: 'growme-91008.firebasestorage.app',
    measurementId: 'G-B8WR1YS0MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqWDP4GHJPtubGWFuNZ-B-9kNFPKjUqT4',
    appId: '1:1062899694013:android:94945b1c4297669f35bad4',
    messagingSenderId: '1062899694013',
    projectId: 'growme-91008',
    storageBucket: 'growme-91008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-jYz4InPOOWipyaKZA8f9AbXqepeLWEE',
    appId: '1:1062899694013:ios:cd92fe7eb238f42335bad4',
    messagingSenderId: '1062899694013',
    projectId: 'growme-91008',
    storageBucket: 'growme-91008.firebasestorage.app',
    iosClientId: '1062899694013-oq391bjcpi02gcdfu0lvr59q1prhlh1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.growmee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-jYz4InPOOWipyaKZA8f9AbXqepeLWEE',
    appId: '1:1062899694013:ios:cd92fe7eb238f42335bad4',
    messagingSenderId: '1062899694013',
    projectId: 'growme-91008',
    storageBucket: 'growme-91008.firebasestorage.app',
    iosClientId: '1062899694013-oq391bjcpi02gcdfu0lvr59q1prhlh1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.growmee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSBm_jojQ3HRt-CI1hFQoyBnZgCuGxv4U',
    appId: '1:1062899694013:web:c9d3dd26b80cae4135bad4',
    messagingSenderId: '1062899694013',
    projectId: 'growme-91008',
    authDomain: 'growme-91008.firebaseapp.com',
    storageBucket: 'growme-91008.firebasestorage.app',
    measurementId: 'G-HL1BTN2EL2',
  );

}