// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArsqnvt0gv8bhyiA2awUXoSWRP2TDX8OM',
    appId: '1:886075402307:web:52da07fd1f23eb8623ccf6',
    messagingSenderId: '886075402307',
    projectId: 'growme-b22c2',
    authDomain: 'growme-b22c2.firebaseapp.com',
    storageBucket: 'growme-b22c2.firebasestorage.app',
    measurementId: 'G-BF0P8RXX98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4WsKD6VlJSg__4QMXL4W8VC__96YjcQI',
    appId: '1:886075402307:android:98636e6efa4b6aeb23ccf6',
    messagingSenderId: '886075402307',
    projectId: 'growme-b22c2',
    storageBucket: 'growme-b22c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsbHkhPAmxPtl44SHGOOsa30XtYo3Qe0k',
    appId: '1:886075402307:ios:cfcc3ffcf23a192623ccf6',
    messagingSenderId: '886075402307',
    projectId: 'growme-b22c2',
    storageBucket: 'growme-b22c2.firebasestorage.app',
    iosBundleId: 'com.example.growmee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsbHkhPAmxPtl44SHGOOsa30XtYo3Qe0k',
    appId: '1:886075402307:ios:cfcc3ffcf23a192623ccf6',
    messagingSenderId: '886075402307',
    projectId: 'growme-b22c2',
    storageBucket: 'growme-b22c2.firebasestorage.app',
    iosBundleId: 'com.example.growmee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArsqnvt0gv8bhyiA2awUXoSWRP2TDX8OM',
    appId: '1:886075402307:web:3b3c67e00e956c7c23ccf6',
    messagingSenderId: '886075402307',
    projectId: 'growme-b22c2',
    authDomain: 'growme-b22c2.firebaseapp.com',
    storageBucket: 'growme-b22c2.firebasestorage.app',
    measurementId: 'G-8GW1K3650M',
  );
}
