// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI6oFybEM0cCOnXs-_A2jyrYMAbgkxiwI',
    appId: '1:465933799387:web:eeacc27cf69885c2c961fe',
    messagingSenderId: '465933799387',
    projectId: 'growme-3e411',
    authDomain: 'growme-3e411.firebaseapp.com',
    storageBucket: 'growme-3e411.firebasestorage.app',
    measurementId: 'G-5P9S7FY4KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATJY3GBl3Ne3lZfKnCnJkFHJJnMi_iIIo',
    appId: '1:465933799387:android:d273e8b35dd0e64ec961fe',
    messagingSenderId: '465933799387',
    projectId: 'growme-3e411',
    storageBucket: 'growme-3e411.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv5m-rfStp8Vc-Rd4F_YYgLG2OmO1UpdY',
    appId: '1:465933799387:ios:eb378d63cde61fbac961fe',
    messagingSenderId: '465933799387',
    projectId: 'growme-3e411',
    storageBucket: 'growme-3e411.firebasestorage.app',
    iosBundleId: 'com.example.growmee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv5m-rfStp8Vc-Rd4F_YYgLG2OmO1UpdY',
    appId: '1:465933799387:ios:eb378d63cde61fbac961fe',
    messagingSenderId: '465933799387',
    projectId: 'growme-3e411',
    storageBucket: 'growme-3e411.firebasestorage.app',
    iosBundleId: 'com.example.growmee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI6oFybEM0cCOnXs-_A2jyrYMAbgkxiwI',
    appId: '1:465933799387:web:67a0b61f8637721cc961fe',
    messagingSenderId: '465933799387',
    projectId: 'growme-3e411',
    authDomain: 'growme-3e411.firebaseapp.com',
    storageBucket: 'growme-3e411.firebasestorage.app',
    measurementId: 'G-NXEM7XZHCN',
  );

}